services:
  postgres:
    image: postgres:16-alpine
    container_name: assignment-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ingestion
    ports:
      - "5434:5432"
    volumes:
      - assignment_postgres_data:/var/lib/postgresql/data
    command: >
      postgres
        -c shared_buffers=256MB
        -c work_mem=64MB
        -c maintenance_work_mem=512MB
        -c max_wal_size=4GB
        -c synchronous_commit=off
        -c checkpoint_completion_target=0.9
        -c effective_io_concurrency=200
        -c wal_level=minimal
        -c max_wal_senders=0
        -c max_connections=50
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 15
    networks:
      - assignment-network
    shm_size: '512mb'

  ingestion:
    build: ./packages/ingestion
    container_name: assignment-ingestion
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ingestion
      API_BASE_URL: http://datasync-dev-alb-101078500.us-east-1.elb.amazonaws.com
      API_KEY: ${API_KEY:}
      WORKER_COUNT: "20"
      BATCH_SIZE: "5000"
      NODE_OPTIONS: "--max-old-space-size=2048"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    networks:
      - assignment-network

volumes:
  assignment_postgres_data:

networks:
  assignment-network:
    driver: bridge
